# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
    # This wants to go before isort & flake8
  - repo: https://github.com/myint/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake # isort should run before black as black sometimes tweaks the isort output
        args: ["--in-place", "--remove-all-unused-imports", "--ignore-init-module-imports"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.4
    hooks:
      - id: blackdoc
        exclude: docs/index.rst
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies: [
            # Type stubs
            types-python-dateutil,
            types-pkg_resources,
            types-PyYAML,
            types-pytz,
            typing-extensions==3.10.0.0,
            numpy,
          ]
