name: test-env
channels:
  - defaults
  - conda-forge
dependencies:
- go
- go-cgo
- git
- python>=3.6
- pip
- pytest
- pytables
- xarray
- pooch
- netcdf4
- dask
- zarr
- pip:
  - -r requirements.txt
